import Hero from "@/components/hero";
import MyModal from "@/components/modal";
import Container from "@/components/container";
import WhyusList from "@/components/whyus-list";

export const metadata = {
  title: "Argya Legal",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <Hero />
      <MyModal />
      <section>
        <Container className="py-40">
          <p className="text-2xl lg:w-5/6 font-light leading-relaxed">
          <span className="text-al-primary font-bold"> Λrgħyä Legal </span>
             is a boutique law firm offering commercial transaction,
            contract management, regulatory compliance training and dispute
            resolution services.
            <br className="mb-5" />
            The firm was set up with an idea of empowering in-house counsels to
            utilise their time efficiently. We understand the limitations of the
            in-house counsels when it comes to involvement in every matter. We
            intend to collaborate with inhouse teams on various work sharing
            models in order to assist and enable them to increase their
            productivity and efficiency allowing them ample time to focus more
            on critical big ticket items having a huge revenue impact for the
            company.
            <br className="mb-5" />
            <span className="font-bold">
              {" "}
              Integrity, Trust, Confidentiality, Teamwork{" "}
            </span>{" "}
            and
            <span className="font-bold"> Exclusivity </span> are the main
            cornerstones on which our firm stands.
            <br className="mb-5" />
            Our team has more than two decades of rich experience having
            practised in courts, worked with law firms and managing and leading
            legal departments of many multinational companies. We understand the
            industry, its nuances and expectations. Our experience helps us to
            quickly identify bottlenecks from an inhouse business perspective
            and provide practical and commercially viable legal solutions for
            complex issues which suit our client’s needs. We provide advice that
            matters.
          </p>
          {/* <p className="text-4xl w-2/3 md:w-1/2 font-light leading-relaxed">
            We build successful{" "}
            <span className="font-bold"> Relationships;</span> treat people with
            <span className="font-bold"> Respect;</span> and achieve exceptional{" "}
            <span className="font-bold">Results</span>.
          </p> */}
        </Container>
        <Container className="pb-40">
          <WhyusList/>
        </Container>
      </section>
    </main>
  );
}
